from objeto import Objeto

class Common:

    def inicializaObjetos():
        listObjetos = []    
        listObjetos.append(Objeto(3,1))
        listObjetos.append(Objeto(8,3))
        listObjetos.append(Objeto(12,1))
        listObjetos.append(Objeto(2,8))
        listObjetos.append(Objeto(8,9))
        listObjetos.append(Objeto(4,3))
        listObjetos.append(Objeto(4,2))
        listObjetos.append(Objeto(5,8))
        listObjetos.append(Objeto(1,5))
        listObjetos.append(Objeto(1,1))
        listObjetos.append(Objeto(8,1))
        listObjetos.append(Objeto(6,6))
        listObjetos.append(Objeto(4,3))
        listObjetos.append(Objeto(3,2))
        listObjetos.append(Objeto(3,5))
        listObjetos.append(Objeto(5,2))
        listObjetos.append(Objeto(7,3))
        listObjetos.append(Objeto(3,8))
        listObjetos.append(Objeto(5,9))
        listObjetos.append(Objeto(7,3))
        listObjetos.append(Objeto(4,2))
        listObjetos.append(Objeto(3,4))
        listObjetos.append(Objeto(7,5))
        listObjetos.append(Objeto(2,4))
        listObjetos.append(Objeto(3,3))
        listObjetos.append(Objeto(5,1))
        listObjetos.append(Objeto(4,3))
        listObjetos.append(Objeto(3,2))
        listObjetos.append(Objeto(7,14))
        listObjetos.append(Objeto(19,32))
        listObjetos.append(Objeto(20,20))
        listObjetos.append(Objeto(21,19))
        listObjetos.append(Objeto(11,15))
        listObjetos.append(Objeto(24,37))
        listObjetos.append(Objeto(13,18))
        listObjetos.append(Objeto(17,13))
        listObjetos.append(Objeto(18,19))
        listObjetos.append(Objeto(6,10))
        listObjetos.append(Objeto(15,15))
        listObjetos.append(Objeto(25,40))
        listObjetos.append(Objeto(12,17))
        listObjetos.append(Objeto(19,39))
        return listObjetos    